import { StyleSheet } from "react-native";
import fonts from "../../styles/fonts";



export const getStyles = (theme) => StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: theme.background,
  },
  scrollContent: {
    padding: 16,
  },
  nav:{
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 1,
  },
  botaodevoltar:{
    width:30,
    height:30,
    marginLeft: 1,
    color:"#0C21C1",
    fontWeight: '300',
    flexDirection: 'row',
  },
  logo:{
    width:200,
    height:100,
  },
  titulo: {
    fontSize: 30,
    fontFamily: fonts.text,
    color: theme.text,
    fontWeight: 'bold',
    paddingVertical:15,
    marginLeft:10,
  },
  titulo2: {
    fontSize: 22,
    fontFamily: fonts.text,
    color: theme.text,
    fontWeight: 'bold',
    marginBottom: 20,
  },
  navinput: {
    width: '100%',
    padding: 10,
    fontSize: 17,
    fontFamily: fonts.text,
    backgroundColor: '#1C58F2',
    borderRadius: 10,
    borderBottomWidth: 0.1,
    borderBottomColor: '#000',
    marginBottom: 10,
    color: theme.text,
  },
  flat: {
    flex: 1,
  },
  containertarefas: {
    backgroundColor: theme.inputBackground,
    borderRadius: 10,
    padding: 10,
    marginBottom: 20,
    flexDirection: 'row',
    alignItems: 'center',
  },
  containerfuncionario: {
    backgroundColor: theme.inputBackground,
    borderRadius: 10,
    padding: 10,
    marginBottom: 10,
    flexDirection: 'row',
    alignItems: 'center',
    alignSelf:"center",
    marginRight:10,
  },
  imag: {
    width: 45,
    height: 45,
    marginLeft: 10,
  },
  imagemfuncionario: {
    width: 90,
    height: 90,
    marginLeft: 10,
    borderRadius:12,
  },
  imagemContainer: {
    borderRadius: 12,
    overflow: 'hidden', 
  },
  textos: {
    marginLeft: 15,
    flex: 1,
  },
  textolistatitulo: {
    color: theme.text,
    fontSize: 18,
    fontWeight: 'bold',
    fontFamily: fonts.text,
  },
  textolistacargo: {
    color: theme.text,
    fontSize: 15,
    fontFamily: fonts.text,
  },
  textofuncionario: {
    color: theme.text,
    fontSize: 28,
    fontWeight: 'bold',
    fontFamily: fonts.text,
  },
  textofuncionariocargo: {
    color: theme.text,
    fontSize: 19,
    fontWeight: '300',
    fontFamily: fonts.text,
  },
  pontuacao: {
    fontSize: 16,
    fontWeight: 'bold',
    color: theme.text,
    fontFamily: fonts.text,
    marginBottom: 10,
    marginTop:3
  },
  pontuacaotext: {
    fontSize: 16,
    fontWeight: 'bold',
    fontFamily: fonts.text,
    marginBottom: 10,
    color:"#5BB14F"
  },
  linha:{
    flexDirection: 'row',
    justifyContent: 'space-between',
    width: '100%',
    marginTop: 10,
    paddingHorizontal: 6,
    marginBottom:28
  },
  voltar:{
    fontSize: 18,
    fontFamily: fonts.text,
    color:"#0C21C1",
    fontWeight: '300',
    width:60,
  },
  areaInput:{
    width: '100%',
    alignItems: 'flex-start',
    marginLeft:20,
    paddingVertical:5,
  },
  texto: {
    fontSize: 18,
    fontFamily: fonts.text,
    fontWeight: 'bold',
    color: theme.text,
    marginBottom: 5,
  },
  input: {
    width:"90%",
    fontSize: 16,
    borderRadius: 6,
    borderWidth: 1,
    borderBottomColor: '#D6D3D1',
    color:theme.text2,
    backgroundColor: theme.inputBackground,
    paddingVertical:8,    
    paddingHorizontal:20,
    marginBottom: 10,
    marginTop: 15,
  },
  inputnaoeditavel: {
    width:"90%",
    fontSize: 16,
    borderRadius: 6,
    borderWidth: 1,
    borderBottomColor: '#D6D3D1',
    backgroundColor: theme.inputBackground4,
    paddingVertical:8,    
    paddingHorizontal:20,
    marginBottom: 10,
    marginTop: 15,
  },
  botaoeditar: {
    backgroundColor: '#1C58F2',
    paddingVertical: 10,
    paddingHorizontal: 30,
    borderRadius: 10,
    alignItems: 'center',
    alignSelf: 'center',
    marginTop: 20,
  },
  botaosair: {
    backgroundColor: '#F21C1C',
    paddingVertical: 10,
    paddingHorizontal: 30,
    borderRadius: 10,
    alignItems: 'flex-start',
    alignSelf: 'flex-start',
    marginTop: 20,
  },
  textoeditar: {
    color: "#ffff",
    fontSize: 16,
    fontFamily: fonts.text,
    fontWeight: 'bold',
  },
  inputfuncionario: {
    backgroundColor: theme.inputBackground,
    marginBottom: 10,
    marginTop: 15,
    borderRadius: 10,
    paddingHorizontal:5,
    justifyContent: 'center',  
    alignItems: 'center',
  },
  textobotao3: {
    fontSize: 13,
    fontFamily: fonts.text,
    fontWeight: 'bold',
    color: theme.text,
    textAlign: 'center',  
  },
  botaomodo: {
    backgroundColor: theme.inputBackground,
    paddingHorizontal: 20,
    borderRadius: 10,
    alignItems: 'center',
    alignSelf: 'center',
  },  
  modalContainer: {
    flex: 1,
    backgroundColor: '#00000080', 
    justifyContent: 'center',
    alignItems: 'center'
  },
  modalContent: {
    width: 300,
    backgroundColor: theme.background,
    borderRadius: 20,
    alignItems: 'center',
    elevation: 5 
  },
  nav2: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'flex-start',   
    width: '100%',       
    padding: 15,
  },
  botaodevoltar: {
    width: 40,
    height: 40,
    justifyContent: 'center',
    zIndex: 1, 
  },
  textfoto: {
    color: theme.text,
    fontSize: 18,
    fontWeight: 'bold',
    fontFamily: fonts.text,
  },
  areafotototal:{
    padding:5,
  },
  areatitulofoto:{
    alignItems: 'flex-start',
    padding:10,
    paddingVertical:12,
  },
  buttonEnviar:{
    padding:15,
    width:150,
    height:150,
    backgroundColor: theme.primary,
    borderRadius:"25%",
    alignItems: 'center',
    justifyContent: 'center',
  },
  areafoto:{
    flexDirection: 'row',
    justifyContent: 'space-evenly',
    width: '100%',
    marginTop: 10,
    paddingHorizontal: 6,
    marginBottom:28
  },  
  button:{
    backgroundColor: theme.inputBackground,
    padding:5,
    marginBottom:25,
    borderRadius:5,
    width:"100%"
  },
  areafoto2:{
    marginTop:20,
    padding:5,
    alignItems: 'column', 
    gap: 3,
  },
  buttonText:{
    color: "#ffffff",
    fontSize: 13,
    fontFamily: fonts.text,
  },
  buttonText2:{
    color: theme.text,
    fontSize: 12,
    fontFamily: fonts.text,
  }
});